# ui accessible at localhost:4200 / 192.168.99.100:4200

version: '3.7'

services:

  web:
    build: Calm
    image: calm-client:v1
    ports:
      - 4200:80
    networks:
      - default

networks:
  default: