## docker compose yml file with a debugging properties. 
version: '3.4'

services:
  calm:
    image: brendanngoran/calm:1.0
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000
      - 80
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js
